#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ProjectSalutis.droid.Resource", IsApplication=true)]

namespace ProjectSalutis.droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::ProjectSalutis.droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::ProjectSalutis.droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::ProjectSalutis.droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::ProjectSalutis.droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::ProjectSalutis.droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::ProjectSalutis.droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::ProjectSalutis.droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::ProjectSalutis.droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::ProjectSalutis.droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::ProjectSalutis.droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::ProjectSalutis.droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::ProjectSalutis.droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::ProjectSalutis.droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::ProjectSalutis.droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::ProjectSalutis.droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::ProjectSalutis.droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::ProjectSalutis.droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::ProjectSalutis.droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::ProjectSalutis.droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::ProjectSalutis.droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::ProjectSalutis.droid.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::com.refractored.fab.Resource.Attribute.fab_colorDisabled = global::ProjectSalutis.droid.Resource.Attribute.fab_colorDisabled;
			global::com.refractored.fab.Resource.Attribute.fab_colorNormal = global::ProjectSalutis.droid.Resource.Attribute.fab_colorNormal;
			global::com.refractored.fab.Resource.Attribute.fab_colorPressed = global::ProjectSalutis.droid.Resource.Attribute.fab_colorPressed;
			global::com.refractored.fab.Resource.Attribute.fab_colorRipple = global::ProjectSalutis.droid.Resource.Attribute.fab_colorRipple;
			global::com.refractored.fab.Resource.Attribute.fab_shadow = global::ProjectSalutis.droid.Resource.Attribute.fab_shadow;
			global::com.refractored.fab.Resource.Attribute.fab_size = global::ProjectSalutis.droid.Resource.Attribute.fab_size;
			global::com.refractored.fab.Resource.Attribute.layoutManager = global::ProjectSalutis.droid.Resource.Attribute.layoutManager;
			global::com.refractored.fab.Resource.Attribute.reverseLayout = global::ProjectSalutis.droid.Resource.Attribute.reverseLayout;
			global::com.refractored.fab.Resource.Attribute.spanCount = global::ProjectSalutis.droid.Resource.Attribute.spanCount;
			global::com.refractored.fab.Resource.Attribute.stackFromEnd = global::ProjectSalutis.droid.Resource.Attribute.stackFromEnd;
			global::com.refractored.fab.Resource.Color.fab_material_blue_500 = global::ProjectSalutis.droid.Resource.Color.fab_material_blue_500;
			global::com.refractored.fab.Resource.Dimension.fab_elevation_lollipop = global::ProjectSalutis.droid.Resource.Dimension.fab_elevation_lollipop;
			global::com.refractored.fab.Resource.Dimension.fab_scroll_threshold = global::ProjectSalutis.droid.Resource.Dimension.fab_scroll_threshold;
			global::com.refractored.fab.Resource.Dimension.fab_shadow_size = global::ProjectSalutis.droid.Resource.Dimension.fab_shadow_size;
			global::com.refractored.fab.Resource.Dimension.fab_size_mini = global::ProjectSalutis.droid.Resource.Dimension.fab_size_mini;
			global::com.refractored.fab.Resource.Dimension.fab_size_normal = global::ProjectSalutis.droid.Resource.Dimension.fab_size_normal;
			global::com.refractored.fab.Resource.Dimension.item_touch_helper_max_drag_scroll_per_frame = global::ProjectSalutis.droid.Resource.Dimension.item_touch_helper_max_drag_scroll_per_frame;
			global::com.refractored.fab.Resource.Drawable.fab_shadow = global::ProjectSalutis.droid.Resource.Drawable.fab_shadow;
			global::com.refractored.fab.Resource.Drawable.fab_shadow_mini = global::ProjectSalutis.droid.Resource.Drawable.fab_shadow_mini;
			global::com.refractored.fab.Resource.Id.item_touch_helper_previous_elevation = global::ProjectSalutis.droid.Resource.Id.item_touch_helper_previous_elevation;
			global::com.refractored.fab.Resource.Id.mini = global::ProjectSalutis.droid.Resource.Id.mini;
			global::com.refractored.fab.Resource.Id.normal = global::ProjectSalutis.droid.Resource.Id.normal;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton = global::ProjectSalutis.droid.Resource.Styleable.FloatingActionButton;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorDisabled = global::ProjectSalutis.droid.Resource.Styleable.FloatingActionButton_fab_colorDisabled;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorNormal = global::ProjectSalutis.droid.Resource.Styleable.FloatingActionButton_fab_colorNormal;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorPressed = global::ProjectSalutis.droid.Resource.Styleable.FloatingActionButton_fab_colorPressed;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorRipple = global::ProjectSalutis.droid.Resource.Styleable.FloatingActionButton_fab_colorRipple;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_shadow = global::ProjectSalutis.droid.Resource.Styleable.FloatingActionButton_fab_shadow;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_size = global::ProjectSalutis.droid.Resource.Styleable.FloatingActionButton_fab_size;
			global::com.refractored.fab.Resource.Styleable.RecyclerView = global::ProjectSalutis.droid.Resource.Styleable.RecyclerView;
			global::com.refractored.fab.Resource.Styleable.RecyclerView_android_orientation = global::ProjectSalutis.droid.Resource.Styleable.RecyclerView_android_orientation;
			global::com.refractored.fab.Resource.Styleable.RecyclerView_layoutManager = global::ProjectSalutis.droid.Resource.Styleable.RecyclerView_layoutManager;
			global::com.refractored.fab.Resource.Styleable.RecyclerView_reverseLayout = global::ProjectSalutis.droid.Resource.Styleable.RecyclerView_reverseLayout;
			global::com.refractored.fab.Resource.Styleable.RecyclerView_spanCount = global::ProjectSalutis.droid.Resource.Styleable.RecyclerView_spanCount;
			global::com.refractored.fab.Resource.Styleable.RecyclerView_stackFromEnd = global::ProjectSalutis.droid.Resource.Styleable.RecyclerView_stackFromEnd;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::ProjectSalutis.droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::ProjectSalutis.droid.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f090002
			public const int goal_durations = 2131296258;
			
			// aapt resource value: 0x7f090001
			public const int goal_frequencies = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int goal_types = 2131296256;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01000a
			public const int MvxBind = 2130771978;
			
			// aapt resource value: 0x7f01000e
			public const int MvxDropDownItemTemplate = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int MvxGroupItemTemplate = 2130771983;
			
			// aapt resource value: 0x7f01000d
			public const int MvxItemTemplate = 2130771981;
			
			// aapt resource value: 0x7f01000b
			public const int MvxLang = 2130771979;
			
			// aapt resource value: 0x7f010010
			public const int MvxSource = 2130771984;
			
			// aapt resource value: 0x7f01000c
			public const int MvxTemplate = 2130771980;
			
			// aapt resource value: 0x7f010006
			public const int fab_colorDisabled = 2130771974;
			
			// aapt resource value: 0x7f010005
			public const int fab_colorNormal = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int fab_colorPressed = 2130771972;
			
			// aapt resource value: 0x7f010007
			public const int fab_colorRipple = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int fab_shadow = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int fab_size = 2130771977;
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070000
			public const int fab_material_blue_500 = 2131165184;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040005
			public const int fab_elevation_lollipop = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int fab_scroll_threshold = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int fab_shadow_size = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int fab_size_mini = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int fab_size_normal = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130968576;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int fab_shadow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int fab_shadow_mini = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_content_new = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int scale = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int splash = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int MvvmCrossTagId = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int MvxBindingTagUnique = 2131034114;
			
			// aapt resource value: 0x7f05000b
			public const int add_button = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int button1 = 2131034124;
			
			// aapt resource value: 0x7f050015
			public const int buttonContact = 2131034133;
			
			// aapt resource value: 0x7f050014
			public const int buttonGoal = 2131034132;
			
			// aapt resource value: 0x7f050013
			public const int buttonJourney = 2131034131;
			
			// aapt resource value: 0x7f05000a
			public const int cancel_button = 2131034122;
			
			// aapt resource value: 0x7f050016
			public const int editText1 = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int editText2 = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int editText3 = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int editText4 = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int editText5 = 2131034138;
			
			// aapt resource value: 0x7f050007
			public const int feeling_scale = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int feeling_seekbar = 2131034120;
			
			// aapt resource value: 0x7f050012
			public const int goalAdd = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int goalDuration = 2131034129;
			
			// aapt resource value: 0x7f050010
			public const int goalFrequency = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int goalQuantifier = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int goalQuantity = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int goalType = 2131034125;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_previous_elevation = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int journey_spinner = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int mini = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int normal = 2131034116;
			
			// aapt resource value: 0x7f050009
			public const int notes_edittext = 2131034121;
			
			// aapt resource value: 0x7f050006
			public const int textView1 = 2131034118;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddtoJourneyView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Contacts = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ContactsEntryLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int CreateGoalView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int FirstView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int GoalListView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int JourneyEntryLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int JourneyView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ListItem_Goal = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int NewContactView = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int SplashScreen = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int app_name = 2131099650;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int Theme_Splash = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FloatingActionButton = new int[] {
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977};
			
			// aapt resource value: 2
			public const int FloatingActionButton_fab_colorDisabled = 2;
			
			// aapt resource value: 1
			public const int FloatingActionButton_fab_colorNormal = 1;
			
			// aapt resource value: 0
			public const int FloatingActionButton_fab_colorPressed = 0;
			
			// aapt resource value: 3
			public const int FloatingActionButton_fab_colorRipple = 3;
			
			// aapt resource value: 4
			public const int FloatingActionButton_fab_shadow = 4;
			
			// aapt resource value: 5
			public const int FloatingActionButton_fab_size = 5;
			
			public static int[] MvxBinding = new int[] {
					2130771978,
					2130771979};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771980};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130771983};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771984};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771981,
					2130771982};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			public static int[] RecyclerView = new int[] {
					16842948,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 1
			public const int RecyclerView_layoutManager = 1;
			
			// aapt resource value: 3
			public const int RecyclerView_reverseLayout = 3;
			
			// aapt resource value: 2
			public const int RecyclerView_spanCount = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_stackFromEnd = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
